name: golang-test
on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: '1.17'

      - name: Set up gotestsum
        run: |
          go install gotest.tools/gotestsum@latest

      - name: Run tests
        run: |
          mkdir -p tmp/test-results
          gotestsum --junitfile tmp/test-results/gotestsum-report.xml ./...

      - uses: actions/upload-artifact@v3
        with:
          name: test-results.xml
          path: tmp/test-results/gotestsum-report.xml
